// _features/solutions/lib/content.ts
import type { Lang } from '@/_shared/types/i18n';

export type SolutionsContent = {
  kicker: string;
  titleLine1: string;
  titleLine2Lead: string;
  titleLine2Accent: string;
  subtitle: string;
  backLabel: string;
  subOptionsPrompt: string;
  generateLabel: string;
  loadingLabel: string;
  loadingSubLabel: string;
  errorLabel: string;
  retryLabel: string;
  resultTitle: string;
  resetLabel: string;
  liveNote: string;
  statsBlocksWord: string;
  statsLevelsWord: string;
  statsCategoriesWord: string;
  legendTitle: string;
  legendCommand: string;
  legendContainer: string;
  legendValue: string;
  narrativeTitle: string;
  ctaHeadline: string;
  ctaBody: string;
  ctaButtonLabel: string;
};

export const content: Record<Lang, SolutionsContent> = {
  es: {
    kicker: 'TU SOLUCIÓN',
    titleLine1: '¿QUÉ QUIERES',
    titleLine2Lead: 'HACER ',
    titleLine2Accent: 'POSIBLE?',
    subtitle: 'Cuéntanos qué quieres transformar. Nosotros encontramos la tecnología para hacerlo realidad.',
    backLabel: '← Volver',
    subOptionsPrompt: '¿Qué quieres conseguir?',
    generateLabel: 'Explorar soluciones →',
    loadingLabel: 'Diseñando tu arquitectura…',
    loadingSubLabel: 'Un modelo de IA está eligiendo los bloques ahora mismo',
    errorLabel: 'No pudimos generar la arquitectura. Intenta de nuevo.',
    retryLabel: 'Reintentar',
    resultTitle: 'Así podría verse tu solución',
    resetLabel: 'Empezar de nuevo',
    liveNote: 'Generado en vivo por IA a partir de tu elección — cambia de opción para ver otra arquitectura distinta.',
    statsBlocksWord: 'bloques',
    statsLevelsWord: 'niveles',
    statsCategoriesWord: 'categorías',
    legendTitle: 'Cómo leer el diagrama',
    legendCommand: 'Comando — un paso en el flujo',
    legendContainer: 'Contenedor — agrupa otros bloques',
    legendValue: 'Dato — se conecta como recurso',
    narrativeTitle: 'Qué construimos y por qué',
    ctaHeadline: '¿Construimos esto juntos?',
    ctaBody: 'Esta es una primera aproximación generada por IA en segundos. Un arquitecto real de Datheón puede afinarla a tu caso exacto, sin costo y sin compromiso.',
    ctaButtonLabel: 'Agendar una consulta gratuita →',
  },
  en: {
    kicker: 'YOUR SOLUTION',
    titleLine1: 'WHAT DO YOU WANT',
    titleLine2Lead: 'TO MAKE ',
    titleLine2Accent: 'POSSIBLE?',
    subtitle: 'Tell us what you want to transform. We find the technology to make it real.',
    backLabel: '← Back',
    subOptionsPrompt: 'What do you want to achieve?',
    generateLabel: 'Explore solutions →',
    loadingLabel: 'Designing your architecture…',
    loadingSubLabel: 'An AI model is picking the blocks right now',
    errorLabel: "We couldn't generate the architecture. Try again.",
    retryLabel: 'Retry',
    resultTitle: 'This is what your solution could look like',
    resetLabel: 'Start over',
    liveNote: 'Generated live by AI from your choice — pick a different option to see another architecture.',
    statsBlocksWord: 'blocks',
    statsLevelsWord: 'levels',
    statsCategoriesWord: 'categories',
    legendTitle: 'How to read the diagram',
    legendCommand: 'Command — a step in the flow',
    legendContainer: 'Container — groups other blocks',
    legendValue: 'Data — connects as a resource',
    narrativeTitle: 'What we built and why',
    ctaHeadline: 'Shall we build this together?',
    ctaBody: 'This is a first pass generated by AI in seconds. A real Datheón architect can tailor it to your exact case, free and with no commitment.',
    ctaButtonLabel: 'Book a free consultation →',
  },
  fr: {
    kicker: 'VOTRE SOLUTION',
    titleLine1: 'QUE VOULEZ-VOUS',
    titleLine2Lead: 'RENDRE ',
    titleLine2Accent: 'POSSIBLE ?',
    subtitle: 'Dites-nous ce que vous voulez transformer. Nous trouvons la technologie pour le concrétiser.',
    backLabel: '← Retour',
    subOptionsPrompt: 'Que voulez-vous accomplir ?',
    generateLabel: 'Explorer les solutions →',
    loadingLabel: 'Conception de votre architecture…',
    loadingSubLabel: "Un modèle d'IA choisit les blocs en ce moment",
    errorLabel: "Impossible de générer l'architecture. Réessayez.",
    retryLabel: 'Réessayer',
    resultTitle: 'Voici à quoi pourrait ressembler votre solution',
    resetLabel: 'Recommencer',
    liveNote: "Généré en direct par l'IA à partir de votre choix — changez d'option pour voir une autre architecture.",
    statsBlocksWord: 'blocs',
    statsLevelsWord: 'niveaux',
    statsCategoriesWord: 'catégories',
    legendTitle: 'Comment lire le diagramme',
    legendCommand: 'Commande — une étape du flux',
    legendContainer: 'Conteneur — regroupe d\'autres blocs',
    legendValue: 'Donnée — se connecte comme ressource',
    narrativeTitle: 'Ce que nous avons construit, et pourquoi',
    ctaHeadline: 'On construit ça ensemble ?',
    ctaBody: "Ceci est une première approche générée par l'IA en quelques secondes. Un architecte Datheón peut l'affiner à votre cas exact, gratuitement et sans engagement.",
    ctaButtonLabel: 'Réserver une consultation gratuite →',
  },
};
